{% set version = "21.2.0" %}

package:
  name: gunicorn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gunicorn/gunicorn-{{ version }}.tar.gz
  sha256: 88ec8bff1d634f98e61b9f65bc4bf3cd918a90806c6f5c48bc5603849ec81033

build:
  # Failing on s390x and also not needed on s390x for mlflow
  skip: True  # [win or s390x]
  skip: True  # [py<35]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  preserve_egg_dir: True
  entry_points:
    - gunicorn=gunicorn.app.wsgiapp:run

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - packaging

test:
  imports:
    - gunicorn
    - gunicorn.app
    - gunicorn.http
    - gunicorn.instrument
    - gunicorn.workers
  commands:
    - gunicorn --help
    - pip check
  requires:
    - pip
    - paste # [py<312]

about:
  home: https://gunicorn.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WSGI HTTP Server for UNIX
  description: |
    Gunicorn pre-fork worker model ported from Ruby's Unicorn project. Gunicorn server is broadly compatible with various web frameworks,simply implemented,light on server resources and fairly speedy.
  doc_url: https://docs.gunicorn.org
  dev_url: https://github.com/benoitc/gunicorn

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jakirkham
    - sodre
