{% set name = "gunicorn" %}
{% set version = "26.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 62b864895d9ebff0b2f9867ba04fe811c93121596540830c9c916d0769668447

build:
  # Windows is not supported by upstream by design
  skip: true  # [win]
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  entry_points:
    - gunicorn = gunicorn.app.wsgiapp:run
    - gunicornc = gunicorn.ctl.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2
  run:
    - python
    - packaging
  run_constrained:
    - gevent >=24.10.1
    - tornado >=6.5.7
    - h2 >=4.4.1
    - gunicorn_h1c >=0.6.9

# Docker tests
{% set ignore_tests = "--ignore=tests/docker" %}
# >  assert "Hello, World!" in response_text
# E  AssertionError: assert 'Hello, World!' in 'HTTP/1.1 200 OK\r\ncontent-type: text/plain\r\n\r\n'
{% set deselect_tests = " --deselect=tests/test_asgi_worker.py::TestASGIIntegration::test_http_request_response" %}
# Randomly failing on CI
{% set ignore_tests = ignore_tests + " --ignore=tests/test_http2_async_connection.py" %}

test:
  source_files:
    - tests
  imports:
    - gunicorn
    - gunicorn.app
    - gunicorn.http
    - gunicorn.instrument
    - gunicorn.workers
  requires:
    - pip
    - h2
    - pytest >=9.0.3
    - pytest-asyncio
  commands:
    - gunicorn --help
    - gunicornc --help
    - pip check
    - pytest -vv tests {{ ignore_tests }} {{ deselect_tests }}

about:
  home: https://gunicorn.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WSGI HTTP Server for UNIX
  description: |
    Gunicorn pre-fork worker model ported from Ruby's Unicorn project. Gunicorn server is broadly compatible with various web frameworks,simply implemented,light on server resources and fairly speedy.
  doc_url: https://docs.gunicorn.org
  dev_url: https://github.com/benoitc/gunicorn

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jakirkham
    - sodre
