{% set name = "gunicorn" %}
{% set version = "24.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f006d110e5cb3102859b4f5cd48335dbd9cc28d0d27cd24ddbdafa6c60929408

build:
  # Windows is not supported by upstream by design
  skip: true  # [win]
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  preserve_egg_dir: true
  entry_points:
    - gunicorn=gunicorn.app.wsgiapp:run

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2
  run:
    - python
    - packaging
  run_constrained:
    - gevent >=24.10.1
    - eventlet >=0.40.3
    - tornado >=6.5.0

test:
  source_files:
    - tests
  imports:
    - gunicorn
    - gunicorn.app
    - gunicorn.http
    - gunicorn.instrument
    - gunicorn.workers
  requires:
    - pip
    - eventlet
    - pytest >=7.2.0
  commands:
    - gunicorn --help
    - pip check
    - pytest -vv tests

about:
  home: https://gunicorn.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WSGI HTTP Server for UNIX
  description: |
    Gunicorn pre-fork worker model ported from Ruby's Unicorn project. Gunicorn server is broadly compatible with various web frameworks,simply implemented,light on server resources and fairly speedy.
  doc_url: https://docs.gunicorn.org
  dev_url: https://github.com/benoitc/gunicorn

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jakirkham
    - sodre
