{% set version = "23.0.0" %}

package:
  name: gunicorn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gunicorn/gunicorn-{{ version }}.tar.gz
  sha256: f014447a0101dc57e294f6c18ca6b40227a4c90e9bdb586042628030cba004ec

build:
  # Windows is not supported by upstream by design
  skip: True  # [win]
  skip: True  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  preserve_egg_dir: True
  entry_points:
    - gunicorn=gunicorn.app.wsgiapp:run

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2
    - wheel
  run:
    - python
    - packaging
    - importlib-metadata # [py<38]
  run_constrained:
    - gevent >=1.4.0
    - eventlet >=0.24.1,!=0.36.0
    - tornado >=0.2

test:
  source_files:
    - tests
  imports:
    - gunicorn
    - gunicorn.app
    - gunicorn.http
    - gunicorn.instrument
    - gunicorn.workers
  requires:
    - pip
    - eventlet
    - pytest >=7.2.0
  commands:
    - gunicorn --help
    - pip check
    # tests/workers/test_ggevent.py: missing gevent >=1.4.0
    - pytest -vv tests --ignore="tests/workers/test_ggevent.py"

about:
  home: https://gunicorn.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WSGI HTTP Server for UNIX
  description: |
    Gunicorn pre-fork worker model ported from Ruby's Unicorn project. Gunicorn server is broadly compatible with various web frameworks,simply implemented,light on server resources and fairly speedy.
  doc_url: https://docs.gunicorn.org
  dev_url: https://github.com/benoitc/gunicorn

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jakirkham
    - sodre
