{% set name = "gunicorn" %}
{% set version = "19.7.0" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version}}.tar.gz
  url: https://github.com/benoitc/gunicorn/archive/{{ version }}.tar.gz
  sha256: ded14b8b6c24a92006ef4131a6a8bfc0b9c858ba48a7cc5247caee56bd735d65
  patches:
    # See https://github.com/conda-forge/staged-recipes/pull/885#discussion_r68602712
    # git diff --no-prefix -- gunicorn/workers/_gaiohttp.py /dev/null
    - no_gaiohttp.patch  # [py2k]

build:
  skip: True  # [win]
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record record.txt
  preserve_egg_dir: True
  entry_points:
    - gunicorn=gunicorn.app.wsgiapp:run
    - gunicorn_django=gunicorn.app.djangoapp:run
    - gunicorn_paster=gunicorn.app.pasterapp:run

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - gunicorn
    - gunicorn.app
    - gunicorn.http
    - gunicorn.instrument
    - gunicorn.workers
  commands:
    - gunicorn --help
    - gunicorn_paster --help
  requires:
    - paste
    - pastedeploy

about:
  home: http://gunicorn.org
  license: MIT
  license_file: LICENSE
  summary: 'WSGI HTTP Server for UNIX'

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jakirkham
