{% set version = "20.0.4" %}

package:
  name: gunicorn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gunicorn/gunicorn-{{ version }}.tar.gz
  sha256: 1904bb2b8a43658807108d59c3f3d56c2b6121a701161de0ddf9ad140073c626

build:
  skip: True  # [win]
  skip: True  # [py<30]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  preserve_egg_dir: True
  entry_points:
    - gunicorn=gunicorn.app.wsgiapp:run

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - gunicorn
    - gunicorn.app
    - gunicorn.http
    - gunicorn.instrument
    - gunicorn.workers
  commands:
    - gunicorn --help
  requires:
    - paste
    - pastedeploy

about:
  home: http://gunicorn.org
  license: MIT
  license_file: LICENSE
  summary: 'WSGI HTTP Server for UNIX'
  description: |
    Gunicorn pre-fork worker model ported from Ruby's Unicorn project.Gunicorn
    server is broadly compatible with various web frameworks,simply
    implemented,light on server resources and fairly speedy.
  doc_url: http://docs.gunicorn.org/en/stable/
  doc_source_url: https://github.com/benoitc/gunicorn/blob/master/docs/source/index.rst
  dev_url: https://github.com/benoitc/gunicorn

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jakirkham
    - sodre
