{% set version = "22.0.0" %}

package:
  name: gunicorn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gunicorn/gunicorn-{{ version }}.tar.gz
  sha256: 4a0b436239ff76fb33f11c07a16482c521a7e09c1ce3cc293c2330afe01bec63

build:
  skip: True  # [win]
  skip: True  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  preserve_egg_dir: True
  entry_points:
    - gunicorn=gunicorn.app.wsgiapp:run

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - packaging

test:
  imports:
    - gunicorn
    - gunicorn.app
    - gunicorn.http
    - gunicorn.instrument
    - gunicorn.workers
  commands:
    - gunicorn --help
    - pip check
  requires:
    - pip
    # - paste
    # - pastedeploy

about:
  home: http://gunicorn.org
  license: MIT
  license_file: LICENSE
  summary: 'WSGI HTTP Server for UNIX'
  description: |
    Gunicorn pre-fork worker model ported from Ruby's Unicorn project.Gunicorn
    server is broadly compatible with various web frameworks,simply
    implemented,light on server resources and fairly speedy.
  doc_url: http://docs.gunicorn.org/en/stable/
  doc_source_url: https://github.com/benoitc/gunicorn/blob/master/docs/source/index.rst
  dev_url: https://github.com/benoitc/gunicorn

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jakirkham
    - sodre
