# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "M+uBNVLmsNLew0G4tV9oXifw3/UhAkXFM1ZY5obkvTPUMJpJ/IfLP/rqmE+1XGUmkhQbROAf4xk7PocxOiny0VoXtdCPGsbgFow7UPXeXgV4LpcEtfISqh7NMZPLLjp1W/P4G+y1AXGAKVR9ozNBCqWUTqvTLl4zIHsuq5ttJ7xYBhZf0A8+xduwD7YImY+jqiukf138Gj+sEc0aEfhm3nTJln/Zl7ss9fx8gNNLKS8n3zbLwRGjXkLP0BqWkRLYskkVypcVPv65OnDAKN0FFg2qr7/aNd3o3SEmRrO4+LINtqyoeGU3rPn5CQBb1SF6o4huarXh9rLHP1h2/u6I8ftwXe10I+z2+VM1RNk3ZlSx0wugmj3bfx7in16neilcUREUUlWhiEOHa30l28faYSPUXu9lAhOe9CUt00ULyNg4juG4AfuEMPO882bWmry2y5mBXxL5qPvnFwQqWkAasCJxO1ahSDXPFDRe8kE8ALmjUi3MQlHXXelMcKbo5mNjqfQSqI4Fns2jV1tB9YnEAjJhfJuL+rRpdLeP9pUdMXvfomCiO+p1Gis9c2Mqe16r7xED+xHznJ9TaIb5BeQqXnnTJfCh0s2tN3FoBrfpz279tC/UeOxbHWHVdYzmpMwiUHqZa84GjlUIOuHcD5xqc+VDUelSyaSXd/RmRXi35fk="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
