travis:
  secure:
    BINSTAR_TOKEN: K10aTWchajzJS0m21DK5l0R2e3IE0kC2O87niZuVtbvPI66CEtGkXjT9WCiVcdRI43lMktLvjLX51ip59tnJTO2VrWQ//aAcOG6fc7b5iuRYtSO2+KmLT3vSOWBL6BS8Gua9fwQeeu0F/7nBoBV2pycpIV1XgcCynA7XCCaDnTJgR/oqqU7ap0QRm1F16PbBR14R0E1vyRN8lIKTcixhRx/MxOlPPVeB+Q3gN9xdK1wkrq2yQmC/xCy4wQSLyQHMkPEvxOrk7X3KZL04EHai+oFfF1K5qA7jVmEuxaGAiRXykOBkTypt9AnNNCZFqVal3LSqEyz1W1dYkkk53lzlYcHdybJFFi4CVjSiCh8eMQqTvBey0Zn5HrN/RhSkuZGnil/K3OR7u6xatj+6oMtBn6DpQGYUdtGtV+ga/Z3irPNNMfxzsMmTiHZgMheENqB0/bPqvCaomCoymylT11LZW8AnIPxqEiqnVmST1HPj9bVIEdL90yZkJRZDjQp3OwpVI9mUMVPXtr2str1X401QdINK21KYG2pm4JZx+KHAULfrNTFeLnpITdkxL/BkSfjXh52PB29f64FgkMaDGZnBZfGu3HMMeeX/jUE4ikgl4wGMrNYM/9BDpto4VJ01P8JKPiw0EPG+t3CtvkP0vkK8TnJLNSoNVXkejQdEf15Ya/I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
