travis:
  secure:
    BINSTAR_TOKEN: DIYSDPOuIhnS2CuMFyjmv7AwmM7j1FS4k+ghmcYfxqdP5WxcHvTARnFJMhpXlkmKZfcgdY6rJB/0SQ4yhCoOPQvGwfcaumlwFNqGg726NTg4IsNO6gX15GMZsySNQie3RUlton1fzWldyX14G9mIyU9TJ5VaKmQeCEcs3PjJKBGcSmLB9lQfKkUA+SEHXRSUjviH0z4yD9XlNSUB3Z0CggHI0TXKJt4fSkTggPn7j4kJb9JOyrvMm4K6jl26GuYthJuhdZ33x4dKKyjYIzXdZTxdk2K2ZJtWc3d8kd9+cfGQZ0mxPZdsSy7c9jwHpfk22Q06SmaDfTl5c/YrSaBTunioZSX4iFaR9JmZDLNsjVJGxmB+9nDTGcw916O3Xf2PzQM7O+wvpOC21lWeg/zFhyVmdXz1bDk5gfi0ikg0w5yOjO0PkYdqM8yDBzjX3q3CETCC/4Ta7MhHjgpRTlTLV9uS3xAL+AtFvcr639dvAMvvtCpVlHt3fOGeVK8sJN12FhJdbs1Aa1VVZ3ODfsf4P9+93Xad+ODXfheTpXORbD371S8XLw0aQ6yp3nN13MlsqBl/YS/nX2w23zQ7gLrXP4FidQ1aShK5ylNr3DdbDHNieCTMPfnhmNEjUjPWS0+DCikYpo3PoHwyZIevCRrvO7mb4FE1cAPSASvLsQbyDqk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
